// utils/penaltyCron.js

/**
 * Daily Penalty Calculation Job
 *
 * Logic:
 *  - Runs daily for all APPROVED mortgage loans
 *  - Finds the latest UNPAID/PARTIAL instalment that is past its due date
 *  - Penalty starts after the due date (with a 3-day grace window from dueDate)
 *  - Penalty accrues daily: loan.dailyPenaltyAmount × days overdue
 *  - Penalty is CAPPED at 1 month from the due date:
 *      penaltyWindow = dueDate → (dueDate + 1 month)
 *    After this window closes, the next month's instalment will have been
 *    generated by the instalment cron and will accrue its own penalties.
 *  - Handles server downtime by catching up missed days (clamped to penalty window)
 *  - Also marks instalments as OVERDUE when past due date and unpaid
 */
export async function processDailyPenalties(prisma, log) {
  log.info("⏰ Starting daily penalty calculation job...");

  // Today at midnight (strip time for clean date comparisons)
  const today = new Date();
  today.setHours(0, 0, 0, 0);

  try {
    // 1. Fetch all APPROVED loans with their UNPAID/PARTIAL instalments
    const loans = await prisma.mortgageLoan.findMany({
      where: { status: "APPROVED" },
      include: {
        instalments: {
          where: {
            status: { in: ["UNPAID", "PARTIAL"] }
          },
          // Descending so the most recent overdue instalment is found first
          orderBy: { monthNumber: "desc" }
        }
      }
    });

    let totalPenaltiesApplied = 0;
    let totalMarkedOverdue    = 0;

    for (const loan of loans) {
      // 2. Find the single "active penalty instalment":
      //    The latest instalment whose due date has passed the 3-day grace window
      const activePenaltyInstalment = loan.instalments.find(inst => {
        const graceEnd = new Date(inst.dueDate);
        graceEnd.setDate(graceEnd.getDate() + 3);
        graceEnd.setHours(0, 0, 0, 0);
        return today > graceEnd;
      });

      if (!activePenaltyInstalment) continue;

      const inst = activePenaltyInstalment;

      // 3. Mark as OVERDUE if still UNPAID
      if (inst.status === "UNPAID") {
        await prisma.mortgageInstalment.update({
          where: { id: inst.id },
          data: { status: "OVERDUE" }
        });
        totalMarkedOverdue++;
        log.info(`  ⚠ Marked Month ${inst.monthNumber} of ${loan.loanNo} as OVERDUE`);
      }

      // 4. Determine penalty window boundaries
      //    Grace end  = dueDate + 3 days  (penalty starts here)
      //    Penalty end = dueDate + 1 month (penalty STOPS here — next month takes over)
      const graceEnd = new Date(inst.dueDate);
      graceEnd.setDate(graceEnd.getDate() + 3);
      graceEnd.setHours(0, 0, 0, 0);

      const penaltyEnd = new Date(inst.dueDate);
      penaltyEnd.setMonth(penaltyEnd.getMonth() + 1);
      penaltyEnd.setHours(0, 0, 0, 0);

      // 5. If today is already past the penalty window, clamp to penaltyEnd
      //    (catches up any missed days without going over the 1-month cap)
      const effectiveToday = today < penaltyEnd ? today : penaltyEnd;

      // Nothing to do if effectiveToday is still within the grace period
      if (effectiveToday <= graceEnd) continue;

      // 6. Calculate how many new days need a penalty applied
      //    Start from: last applied date, or graceEnd if never applied before
      const lastApplied = inst.lastPenaltyAppliedAt
        ? (() => {
            const d = new Date(inst.lastPenaltyAppliedAt);
            d.setHours(0, 0, 0, 0);
            return d;
          })()
        : graceEnd;

      const msInDay         = 1000 * 60 * 60 * 24;
      const daysToPenalize  = Math.floor((effectiveToday - lastApplied) / msInDay);

      // 7. Apply penalty only if there are uncounted days
      if (daysToPenalize > 0) {
        const penaltyToAdd = Number(loan.dailyPenaltyAmount) * daysToPenalize;

        await prisma.mortgageInstalment.update({
          where: { id: inst.id },
          data: {
            penaltyAmount:        { increment: penaltyToAdd },
            remainingDue:         { increment: penaltyToAdd },
            lastPenaltyAppliedAt: effectiveToday,
          }
        });

        totalPenaltiesApplied++;
        log.info(
          `  ✔ Penalty +${penaltyToAdd.toFixed(2)} (${daysToPenalize} day(s)) ` +
          `→ Loan ${loan.loanNo} Month ${inst.monthNumber} ` +
          `[window: ${graceEnd.toDateString()} → ${penaltyEnd.toDateString()}]`
        );
      }
    }

    log.info(
      `⏰ Penalty job complete. ` +
      `Applied to ${totalPenaltiesApplied} instalment(s), ` +
      `marked ${totalMarkedOverdue} as OVERDUE.`
    );
    return { success: true, totalPenaltiesApplied, totalMarkedOverdue };

  } catch (error) {
    log.error("❌ Error in daily penalty job:", error);
    throw error;
  }
}
